package com.google.code.jskills.dal.entities;

// Generated 25.06.2013 17:52:09 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApplicationSettingsEntity generated by hbm2java
 */
@Entity
@Table(name = "APPLICATION_SETTINGS", schema = "PUBLIC", catalog = "PUBLIC")
public class ApplicationSettingsEntity implements java.io.Serializable {

	private Integer id;
	private String propertyValue;

	public ApplicationSettingsEntity() {
	}

	public ApplicationSettingsEntity(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PROPERTY_VALUE", nullable = false, length = 256)
	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

}
