package com.google.code.jskills.dal.entities;

// Generated 25.06.2013 17:52:09 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GroupEntity generated by hbm2java
 */
@Entity
@Table(name = "GROUP_", schema = "PUBLIC", catalog = "PUBLIC", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class GroupEntity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<GroupRoleEntity> groupRoleEntities = new HashSet<GroupRoleEntity>(
			0);
	private Set<UserGroupEntity> userGroupEntities = new HashSet<UserGroupEntity>(
			0);

	public GroupEntity() {
	}

	public GroupEntity(String name) {
		this.name = name;
	}

	public GroupEntity(String name, String description,
			Set<GroupRoleEntity> groupRoleEntities,
			Set<UserGroupEntity> userGroupEntities) {
		this.name = name;
		this.description = description;
		this.groupRoleEntities = groupRoleEntities;
		this.userGroupEntities = userGroupEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupEntity")
	public Set<GroupRoleEntity> getGroupRoleEntities() {
		return this.groupRoleEntities;
	}

	public void setGroupRoleEntities(Set<GroupRoleEntity> groupRoleEntities) {
		this.groupRoleEntities = groupRoleEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupEntity")
	public Set<UserGroupEntity> getUserGroupEntities() {
		return this.userGroupEntities;
	}

	public void setUserGroupEntities(Set<UserGroupEntity> userGroupEntities) {
		this.userGroupEntities = userGroupEntities;
	}

}
