package com.google.code.jskills.dal.entities;

// Generated 25.06.2013 17:52:09 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePermissionEntityId generated by hbm2java
 */
@Embeddable
public class RolePermissionEntityId implements java.io.Serializable {

	private int roleId;
	private int permissionId;

	public RolePermissionEntityId() {
	}

	public RolePermissionEntityId(int roleId, int permissionId) {
		this.roleId = roleId;
		this.permissionId = permissionId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "PERMISSION_ID", nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePermissionEntityId))
			return false;
		RolePermissionEntityId castOther = (RolePermissionEntityId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getPermissionId() == castOther.getPermissionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getPermissionId();
		return result;
	}

}
