package com.google.code.jskills.dal.entities;

// Generated 25.06.2013 17:52:09 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Test2questionEntity generated by hbm2java
 */
@Entity
@Table(name = "TEST2QUESTION", schema = "PUBLIC", catalog = "PUBLIC")
public class Test2questionEntity implements java.io.Serializable {

	private Test2questionEntityId id;
	private QuestionEntity questionEntity;
	private TestEntity testEntity;

	public Test2questionEntity() {
	}

	public Test2questionEntity(Test2questionEntityId id,
			QuestionEntity questionEntity, TestEntity testEntity) {
		this.id = id;
		this.questionEntity = questionEntity;
		this.testEntity = testEntity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "testId", column = @Column(name = "TEST_ID", nullable = false)),
			@AttributeOverride(name = "questionId", column = @Column(name = "QUESTION_ID", nullable = false)) })
	public Test2questionEntityId getId() {
		return this.id;
	}

	public void setId(Test2questionEntityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID", nullable = false, insertable = false, updatable = false)
	public QuestionEntity getQuestionEntity() {
		return this.questionEntity;
	}

	public void setQuestionEntity(QuestionEntity questionEntity) {
		this.questionEntity = questionEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_ID", nullable = false, insertable = false, updatable = false)
	public TestEntity getTestEntity() {
		return this.testEntity;
	}

	public void setTestEntity(TestEntity testEntity) {
		this.testEntity = testEntity;
	}

}
