package com.google.code.jskills.dal.entities;

// Generated 25.06.2013 17:52:09 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupRoleEntityId generated by hbm2java
 */
@Embeddable
public class GroupRoleEntityId implements java.io.Serializable {

	private int groupId;
	private int roleId;

	public GroupRoleEntityId() {
	}

	public GroupRoleEntityId(int groupId, int roleId) {
		this.groupId = groupId;
		this.roleId = roleId;
	}

	@Column(name = "GROUP_ID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupRoleEntityId))
			return false;
		GroupRoleEntityId castOther = (GroupRoleEntityId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
