package com.google.code.jskills.dal.entities;

// Generated 25.06.2013 17:52:09 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Test2questionEntityId generated by hbm2java
 */
@Embeddable
public class Test2questionEntityId implements java.io.Serializable {

	private int testId;
	private int questionId;

	public Test2questionEntityId() {
	}

	public Test2questionEntityId(int testId, int questionId) {
		this.testId = testId;
		this.questionId = questionId;
	}

	@Column(name = "TEST_ID", nullable = false)
	public int getTestId() {
		return this.testId;
	}

	public void setTestId(int testId) {
		this.testId = testId;
	}

	@Column(name = "QUESTION_ID", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Test2questionEntityId))
			return false;
		Test2questionEntityId castOther = (Test2questionEntityId) other;

		return (this.getTestId() == castOther.getTestId())
				&& (this.getQuestionId() == castOther.getQuestionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTestId();
		result = 37 * result + this.getQuestionId();
		return result;
	}

}
